# Site settings
name: Oleh Antonyuk
email: oleh11@gmail.com

keywords: "University of Illinois at Chicago, Graduate, Masters, Management Information Systems, Project Management, Business Analyst, Data Analyst"
skills: "Java, Python, C++, HTML, R, SQL  \n https://github.com/oleh11"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/oleh-antonyuk
  #- title: medium
    #url: 
  #- title: twitter
   # url: 
   #title: github
    #url:https://github.com/oleh11
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
